# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b754f6cbfd37a4bd4814bf38516b37af54cc15c04090a20b640fa50aa9ac2fb9cad057b10bc1b5c342563b03983ec43f09097520ae9ac7e518b9fc2599448af4

test:
  secret_key_base: 6a4349d5f2632421fe8566a141a233ac40bf7141a760a164f743ea1669b529807e4fbf716eef18ee289696725c68f541a8ce356865669cfcbb13ef2a01790038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
